### ISSUE TITLE
str错误

### ISSUE THREAD

**Issue by todoXu** [gfriends/gfriends-inputer#41]
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 807, in <module>
TypeError: can only concatenate str (not "NoneType") to str
[9424] Failed to execute script 'Gfriends Inputer' due to unhandled exception!

看了下807行
logger.info('代理配置：' + str(proxies) + '，IP归属地：' + public_ip)

proxies定义在 779行
if Proxy:
    proxies = {'http': Proxy, 'https': Proxy}
else:
    proxies = None

proxies 这个要判断下是不是非空

**Comment by xinxin8816** [comment]
新版本已修复
原因是 public_ip 变量需要转换为字符串
________________________________
From: todoXu ***@***.***>
Sent: Sunday, July 31, 2022 12:42:43 AM
To: gfriends/gfriends-inputer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gfriends/gfriends-inputer] str错误 (Issue #41)


Traceback (most recent call last):
File "Gfriends Inputer.py", line 807, in
TypeError: can only concatenate str (not "NoneType") to str
[9424] Failed to execute script 'Gfriends Inputer' due to unhandled exception!

看了下807行
logger.info('代理配置：' + str(proxies) + '，IP归属地：' + public_ip)

局部代理

if Proxy:
proxies = {'http': Proxy, 'https': Proxy}
else:
proxies = None

局部代理

if Proxy:
proxies = {'http': Proxy, 'https': Proxy}
else:
proxies = None

proxies 这个要判断下是不是非空

proxies 这个要判断下是不是非空

―
